//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group11_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.SHOPPING_CART = new HashSet<SHOPPING_CART>();
            this.USER_COMMENTS = new HashSet<USER_COMMENTS>();
            this.USER_QUERY = new HashSet<USER_QUERY>();
        }
    
        public string customerID { get; set; }
        public string customerName { get; set; }
        public string customerShippingAddress { get; set; }
        public string customerBillingAddress { get; set; }
        public Nullable<System.DateTime> customerDOB { get; set; }
        public string customerGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOPPING_CART> SHOPPING_CART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_COMMENTS> USER_COMMENTS { get; set; }
        public virtual USER_PASSWORD USER_PASSWORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_QUERY> USER_QUERY { get; set; }
    }
}
