//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group11_iCLOTHINGApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group11_iCLOTHINGDBEntities : DbContext
    {
        public Group11_iCLOTHINGDBEntities()
            : base("name=Group11_iCLOTHINGDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABOUT_US> ABOUT_US { get; set; }
        public virtual DbSet<ADMINISTRATOR> ADMINISTRATOR { get; set; }
        public virtual DbSet<BRAND> BRAND { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<EMAIL> EMAIL { get; set; }
        public virtual DbSet<ITEM_DELIVERY> ITEM_DELIVERY { get; set; }
        public virtual DbSet<ORDER_STATUS> ORDER_STATUS { get; set; }
        public virtual DbSet<ITEM> ITEM { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<SHOPPING_CART> SHOPPING_CART { get; set; }
        public virtual DbSet<USER_COMMENTS> USER_COMMENTS { get; set; }
        public virtual DbSet<USER_PASSWORD> USER_PASSWORD { get; set; }
        public virtual DbSet<USER_QUERY> USER_QUERY { get; set; }
    }
}
