//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group11_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_STATUS
    {
        public int statusID { get; set; }
        public int cartID { get; set; }
        public int adminID { get; set; }
        public string orderStatus { get; set; }
        public Nullable<System.DateTime> statusDate { get; set; }
    
        public virtual ADMINISTRATOR ADMINISTRATOR { get; set; }
        public virtual SHOPPING_CART SHOPPING_CART { get; set; }
    }
}
