//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group11_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.SHOPPING_CART = new HashSet<SHOPPING_CART>();
        }
    
        public string productID { get; set; }
        public string brandID { get; set; }
        public string categoryID { get; set; }
        public string adminID { get; set; }
        public string departmentID { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public double productPrice { get; set; }
        public int productQty { get; set; }
    
        public virtual ADMINISTRATOR ADMINISTRATOR { get; set; }
        public virtual BRAND BRAND { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOPPING_CART> SHOPPING_CART { get; set; }
    }
}
